### ISSUE TITLE
Css tag nested rules

### ISSUE THREAD

**Issue by mcm-odoo** [odoo/owl#592]
With owl.tags.css, this
```css
div {
  [role=button], button {
    color: red;
  }
}
```
results in
```css
div [role=button], button {
  color: red;
}
```
it should be
```css
div [role=button], div button {
  color: red;
}
```
